# Generated by Django 4.2.30 on 2026-05-14 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('hospital', 'Hospital'), ('ambulance_service', 'Ambulance Service')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('institutional_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10)),
                ('institutional_status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('institutional_rejection_reason', models.TextField(blank=True, default='')),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('facility_name', models.CharField(blank=True, default='', max_length=255)),
                ('facility_type', models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public'), ('clinic', 'Clinic')], default='', max_length=20)),
                ('facility_registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('admin_contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('admin_title', models.CharField(blank=True, default='', max_length=100)),
                ('admin_phone', models.CharField(blank=True, default='', max_length=20)),
                ('official_address', models.TextField(blank=True, default='')),
                ('province', models.CharField(blank=True, default='', max_length=100)),
                ('has_emergency_unit', models.BooleanField(default=False)),
                ('ed_phone', models.CharField(blank=True, default='', help_text='Emergency department direct phone number.', max_length=20)),
                ('departments', models.JSONField(blank=True, default=list, help_text='List of department names available at this facility.')),
                ('visiting_hours', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('service_name', models.CharField(blank=True, default='', max_length=255)),
                ('service_type', models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public / Government')], default='', max_length=20)),
                ('license_number', models.CharField(blank=True, default='', help_text='Official EMS operating license number.', max_length=100)),
                ('dispatch_phone', models.CharField(blank=True, default='', max_length=20)),
                ('dispatch_address', models.CharField(blank=True, default='', max_length=255)),
                ('base_address', models.TextField(blank=True, default='', help_text='Physical base/depot address of the ambulance service.')),
                ('operational_areas', models.JSONField(blank=True, default=list, help_text='List of suburb/city strings this service covers.')),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('number_of_active_ambulances', models.PositiveSmallIntegerField(default=0)),
                ('active_units', models.PositiveSmallIntegerField(default=0, help_text='Number of units currently active and on the road.')),
                ('preferred_hospitals', models.JSONField(blank=True, default=list, help_text='List of MERA-registered hospital names this service typically uses.')),
                ('is_available', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
            },
        ),
        migrations.CreateModel(
            name='InstitutionalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('health_facility_certificate', 'Health Facility Certificate'), ('cipc_registration', 'CIPC Registration Document'), ('fleet_insurance', 'Fleet Insurance Certificate'), ('ems_operating_license', 'EMS Operating License'), ('hpcsa_doh_registration', 'HPCSA / DoH Registration'), ('other', 'Other')], max_length=40)),
                ('file', models.FileField(upload_to='institutional_docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Institutional Document',
                'verbose_name_plural': 'Institutional Documents',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['institutional_status'], name='accounts_us_institu_ca0d90_idx'),
        ),
    ]
