# Generated by Django 4.2.30 on 2026-07-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('hospital', 'Hospital'), ('ambulance_service', 'Ambulance Service'), ('hospital_admin', 'Hospital Admin'), ('ambulance_admin', 'Ambulance Admin'), ('emt', 'EMT'), ('mera_admin', 'MERA Admin')], db_index=True, max_length=20),
        ),
    ]
