# Generated by Django 4.2.30 on 2026-07-25 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ambulance_service',
            field=models.ForeignKey(blank=True, help_text="Only populated when role=EMT — the ambulance_admin (or legacy ambulance_service) account this EMT works under. Access an ambulance admin's crew via `ambulance_admin_user.emts.all()`.", limit_choices_to={'role__in': {'ambulance_admin', 'ambulance_service'}}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emts', to=settings.AUTH_USER_MODEL),
        ),
    ]
