# Generated by Django 4.2.30 on 2026-05-14 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('active', 'Active'), ('dispatched', 'Dispatched'), ('on_the_way', 'On the Way'), ('arrived_on_scene', 'Arrived on Scene'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending_confirmation', max_length=30)),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=10)),
                ('activation_method', models.CharField(choices=[('manual', 'Manual (Patient confirmed)'), ('auto', 'Auto-confirmed (Timer expired)'), ('offline', 'Offline (Queued and transmitted)')], default='manual', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_accuracy_metres', models.FloatField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('eta_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('was_offline_queued', models.BooleanField(default=False)),
                ('offline_queued_at', models.DateTimeField(blank=True, null=True)),
                ('medical_profile_access_granted', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambulance_service', models.ForeignKey(blank=True, limit_choices_to={'role': 'ambulance_service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_as_responder', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_cancelled', to=settings.AUTH_USER_MODEL)),
                ('destination_hospital', models.ForeignKey(blank=True, limit_choices_to={'role': 'hospital'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_as_destination', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.PROTECT, related_name='incidents_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chief_complaint', models.TextField(help_text='Presenting condition as found on scene.')),
                ('treatment_administered', models.TextField(help_text='Step-by-step treatment given.')),
                ('blood_pressure', models.CharField(blank=True, default='', max_length=20)),
                ('spo2', models.CharField(blank=True, default='', max_length=10, verbose_name='SpO₂ (%)')),
                ('heart_rate', models.CharField(blank=True, default='', max_length=10)),
                ('medications_given', models.TextField(blank=True, default='')),
                ('additional_notes', models.TextField(blank=True, default='')),
                ('is_draft', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authored_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_notes_authored', to=settings.AUTH_USER_MODEL)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_note', to='emergencies.incident')),
            ],
            options={
                'verbose_name': 'Treatment Note',
                'verbose_name_plural': 'Treatment Notes',
            },
        ),
        migrations.CreateModel(
            name='EmergencyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('sos_triggered', 'SOS Triggered'), ('sos_confirmed', 'SOS Confirmed'), ('sos_auto_confirmed', 'SOS Auto-Confirmed'), ('sos_cancelled', 'SOS Cancelled'), ('ambulance_notified', 'Ambulance Notified'), ('ambulance_accepted', 'Ambulance Accepted'), ('dispatched', 'Dispatched'), ('on_the_way', 'On the Way'), ('arrived_on_scene', 'Arrived on Scene'), ('hospital_notified', 'Hospital Notified'), ('treatment_notes_submitted', 'Treatment Notes Submitted'), ('completed', 'Completed'), ('contacts_notified', 'Emergency Contacts Notified'), ('offline_queued', 'Alert Queued Offline'), ('offline_transmitted', 'Offline Alert Transmitted')], max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this event (null for system events).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_log_actions', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='emergencies.incident')),
            ],
            options={
                'verbose_name': 'Emergency Log Entry',
                'verbose_name_plural': 'Emergency Log Entries',
                'ordering': ['logged_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='emergencies_status_ee4fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['patient', 'status'], name='emergencies_patient_471e38_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['ambulance_service', 'status'], name='emergencies_ambulan_aadfd6_idx'),
        ),
    ]
