# Generated by Django 4.2.30 on 2026-08-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='ambulance_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='ambulance_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
