# Generated by Django 4.2.30 on 2026-09-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0002_incident_ambulance_lat_incident_ambulance_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='emergency_contact_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
