# Generated by Django 4.2.30 on 2026-09-23 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import emergencies.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emergencies', '0003_incident_emergency_contact_alert_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='activation_method',
            field=models.CharField(choices=[('manual', 'Manual (Patient confirmed)'), ('auto', 'Auto-confirmed (Timer expired)'), ('offline', 'Offline (Queued and transmitted)'), ('nfc_bystander', 'NFC Tag (Bystander triggered)')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='NFCTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=emergencies.models._generate_nfc_token, max_length=64, unique=True)),
                ('short_code', models.CharField(db_index=True, default=emergencies.models._generate_nfc_short_code, max_length=8, unique=True)),
                ('paired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, limit_choices_to={'role': 'patient'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NFC Tag',
                'verbose_name_plural': 'NFC Tags',
                'ordering': ['-created_at'],
            },
        ),
    ]
