# Generated by Django 4.2.30 on 2026-09-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0004_alter_incident_activation_method_nfctag'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfctag',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
