# Generated by Django 4.2.30 on 2026-09-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='patient_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='patient_response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
