# Generated by Django 4.2.30 on 2026-05-14 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('chronic_conditions', models.TextField(blank=True, default='', help_text='Comma-separated or free text list of chronic conditions.')),
                ('current_medications', models.TextField(blank=True, default='', help_text='Current medication names and dosages.')),
                ('known_allergies', models.TextField(blank=True, default='', help_text='Known allergies (medications, food, environmental).')),
                ('paramedic_notes', models.TextField(blank=True, default='', help_text='Optional notes for paramedics (e.g. carries EpiPen at all times).')),
                ('verification_status', models.CharField(choices=[('unsubmitted', 'Unsubmitted'), ('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('verified', 'Verified'), ('flagged', 'Flagged — In-Person Visit Required'), ('info_requested', 'More Information Requested')], db_index=True, default='unsubmitted', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('data_sharing_consent', models.BooleanField(default=False)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('consent_withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_updated', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'hospital'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Profile',
                'verbose_name_plural': 'Medical Profiles',
            },
        ),
    ]
