# Generated by Django 4.2.30 on 2026-07-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='ai_chatbot_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='ai_chatbot_consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='ai_chatbot_consent_withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
